### PR TITLE
Palmeri lecture

### PR DESCRIPTION
**Pull request by anikamukherji**
Not the best notes in the world, but hopefully they trigger some recall

@mlp6

### CODE REVIEW

**Comment by anikamukherji** [comment]
@mlp6 good call! done

**Comment by mlp6** [comment]
@anikamukherji all yours to squash-n-merge.  Thanks!

**Comment by anikamukherji** [comment]
@mlp6 I would love to but I can't because I don't have write access!

**Comment by mlp6** [comment]
oh bugger... I'll take care of it.

**Pull request merged**
